# Etapa 1: Build do React
FROM node:22-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Servidor Nginx para servir a aplicação
FROM nginx:stable-alpine

# Remove arquivos padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos gerados pelo build do React
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia um arquivo de configuração customizado para o Nginx
COPY dc/nginx.prod.conf /etc/nginx/conf.d/default.conf

# Expõe a porta padrão do Nginx
EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]
